/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Studentdb;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.MessageFormat;


/**
 *
 * @author User
 */
public class Studentdb extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel();
    private Object finantare;
    /**
     * Creates new form MovieEntry
     */
    public Studentdb() {
        initComponents();      
        Object col[] = {
            "id", "name", "prenume", "Genul", "datanasteri", 
            "Cursul", "Media", "limba", "Promotia", "finantare", "Frecventa"
        };
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        conn = Studentdb.ConnectDB();
        
        updateTable();
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnAddNew = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prenume = new javax.swing.JTextField();
        Limbajul = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cursul = new javax.swing.JTextField();
        mediea = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        frecventa = new javax.swing.JLabel();
        Promotie = new javax.swing.JTextField();
        data = new javax.swing.JTextField();
        Frecventa = new javax.swing.JComboBox<>();
        fiinantare = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student db");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setBackground(new java.awt.Color(51, 51, 51));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(51, 51, 51));
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 180, 40));

        jbtnAddNew.setBackground(new java.awt.Color(51, 51, 51));
        jbtnAddNew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnAddNew.setForeground(new java.awt.Color(51, 51, 51));
        jbtnAddNew.setText("Adauga Student");
        jbtnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddNewActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, 40));

        jbtnUpdate.setBackground(new java.awt.Color(51, 51, 51));
        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnUpdate.setForeground(new java.awt.Color(51, 51, 51));
        jbtnUpdate.setText("Actualizare");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 180, 40));

        jbtnExit.setBackground(new java.awt.Color(51, 51, 51));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(51, 51, 51));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 180, 40));

        jbtnDelete.setBackground(new java.awt.Color(51, 51, 51));
        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDelete.setForeground(new java.awt.Color(51, 51, 51));
        jbtnDelete.setText("Sterge");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 1330, 60));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Nume", "Prenume", "Genul", "Data nasteri", "Cursul", "Media", "Limba de instruire", "Promotia", "Tipul de finantare", "Frecventa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 27, 1310, 420));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 330, 1330, 460));

        jPanel3.setBackground(new java.awt.Color(0, 153, 102));
        jPanel3.setForeground(new java.awt.Color(0, 102, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        id.setBackground(new java.awt.Color(204, 255, 204));
        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 170, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nume");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        name.setBackground(new java.awt.Color(51, 51, 51));
        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 170, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Genul");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prenume");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        prenume.setBackground(new java.awt.Color(51, 51, 51));
        prenume.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prenume.setForeground(new java.awt.Color(255, 255, 255));
        prenume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenumeActionPerformed(evt);
            }
        });
        jPanel3.add(prenume, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 170, 40));

        Limbajul.setBackground(new java.awt.Color(51, 51, 51));
        Limbajul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Limbajul.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(Limbajul, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 170, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data nasteri");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, 30));

        cursul.setBackground(new java.awt.Color(51, 51, 51));
        cursul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cursul.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(cursul, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 170, 40));

        mediea.setBackground(new java.awt.Color(51, 51, 51));
        mediea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mediea.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(mediea, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 170, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Media");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        gen.setBackground(new java.awt.Color(51, 51, 51));
        gen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gen.setForeground(new java.awt.Color(255, 255, 255));
        gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genActionPerformed(evt);
            }
        });
        jPanel3.add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 170, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Limbajul de instruire");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tipul de finantare");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        frecventa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        frecventa.setForeground(new java.awt.Color(255, 255, 255));
        frecventa.setText("Frecventa");
        jPanel3.add(frecventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, -1, -1));

        Promotie.setBackground(new java.awt.Color(51, 51, 51));
        Promotie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Promotie.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(Promotie, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 220, 40));

        data.setBackground(new java.awt.Color(51, 51, 51));
        data.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        data.setForeground(new java.awt.Color(255, 255, 255));
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        jPanel3.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 170, 40));

        Frecventa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Frecventa.setForeground(new java.awt.Color(255, 255, 255));
        Frecventa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "La zi", "Redusa" }));
        Frecventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrecventaActionPerformed(evt);
            }
        });
        jPanel3.add(Frecventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, 220, 40));

        fiinantare.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fiinantare.setForeground(new java.awt.Color(255, 255, 255));
        fiinantare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buget", "Contract" }));
        fiinantare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiinantareActionPerformed(evt);
            }
        });
        jPanel3.add(fiinantare, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 220, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Promotia");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Cursul");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 100, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1330, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddNewActionPerformed
    DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
        mod.setRowCount(0);
               
        
        String sql = "INSERT INTO dataform(id, name, Prenume, Genul, Datanasteri, Cursul, Media, " 
                    +  "Limba,  Promotia,finantare,Frecventa )VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            
        try
        {
            pst = conn.prepareStatement(sql);
            pst.setString(1, id.getText());
            pst.setString(2, name.getText());
            pst.setString(3, prenume.getText());
            pst.setString(4, gen.getText());
            pst.setString(5, data.getText());
            pst.setString(6, cursul.getText());
            pst.setString(7, mediea.getText());
            pst.setString(8, Limbajul.getText());
            pst.setString(9, (String) Promotie.getText());
            pst.setString(10, (String) fiinantare.getSelectedItem());
            pst.setString(11, (String) Frecventa.getSelectedItem());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Date au fost cu succes adaugate");
            rs.close();
            pst.close();

        }
        catch (SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        updateTable();
        DefaultTableModel iModel = (DefaultTableModel) jTable1.getModel();
        
        if(jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "actualizare facuta cu succes",
                        "Student System", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_jbtnAddNewActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void fiinantareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiinantareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiinantareActionPerformed
    public static Connection ConnectDB() {
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:dataform.db"); //connect to database
            return conn;
        }
        catch (ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
       return null;
        }
    }
    
    public void updateTable() {
        conn = Studentdb.ConnectDB();
        
        if (conn != null) {
            String sql = "Select id, name, Prenume, Genul, datanasteri,Cursul, Media," 
                    +  "Limba, Promotia, finantare, Frecventa from dataform";
            
        try
        {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Object[] columnData = new Object[11];
            
        
            while (rs.next()) {
                columnData[0] = rs.getString("id");
                columnData[1] = rs.getString("name");
                columnData[2] = rs.getString("prenume");
                columnData[3] = rs.getString("Genul");
                columnData[4] = rs.getString("datanasteri");
                columnData[5] = rs.getString("Cursul");
                columnData[6] = rs.getString("Media");
                columnData[7] = rs.getString("Limba");
                columnData[8] = rs.getString("Promotia");
                columnData[9] = rs.getString("finantare"); 
                columnData[10] = rs.getString("Frecventa");
                model.addRow(columnData);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
     
        }
 
     
        }
    }
    
    
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Exit?",
                "Student db for",
               JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
       try 
       {
           id.setText(null);
           name.setText(null);
           prenume.setText(null);
           gen.setText(null);
           data.setText(null);
           cursul.setText(null);
           mediea.setText(null);
           Limbajul.setText(null);
           Promotie.setText(null);
           fiinantare.setSelectedIndex(0);
           Frecventa.setSelectedIndex(0);
       }
       catch (Exception e)
               {
                   JOptionPane.showMessageDialog(null, e);
               }
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed

        updateTable();
        DefaultTableModel iModel = (DefaultTableModel) jTable1.getModel();
        
        if(jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Date Actualizate!",
                        "Student db", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed

        DefaultTableModel iModel = (DefaultTableModel) jTable1.getModel();
                
              String sql = " Doriti sa stergeti = ?";
        if (jTable1.getSelectedRow() == -1) {
            if(jTable1.getRowCount()==0) {
                         
                JOptionPane.showMessageDialog(null, "Nu exista date de sters", 
                        "introducerea Datelor", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Selectati rindul care vreti sal stergeti", 
                        "stergere", JOptionPane.OK_OPTION);
            }
            }else{   
            try {           
                int row = jTable1.getSelectedRow();
                String value = jTable1.getModel().getValueAt(row, 0).toString();              
                String id = value;           
                
                pst = conn.prepareStatement(sql);               
                pst.setString(1, id);
                
               pst.executeUpdate();
            }
            catch (NumberFormatException | SQLException e){
                System.out.println(e.getMessage());
            }                   
                  model.removeRow(jTable1.getSelectedRow());                                  
               }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void FrecventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrecventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FrecventaActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void prenumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenumeActionPerformed

    private void genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studentdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studentdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studentdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studentdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Studentdb().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Frecventa;
    private javax.swing.JTextField Limbajul;
    private javax.swing.JTextField Promotie;
    private javax.swing.JTextField cursul;
    private javax.swing.JTextField data;
    private javax.swing.JComboBox<String> fiinantare;
    private javax.swing.JLabel frecventa;
    private javax.swing.JTextField gen;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAddNew;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField mediea;
    private javax.swing.JTextField name;
    private javax.swing.JTextField prenume;
    // End of variables declaration//GEN-END:variables
}
